name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    ci-build:
        runs-on: ubuntu-latest
        container:
            image: debian:trixie
        defaults:
            run:
                shell: bash
        steps:
        - name: Checks-out
          uses: actions/checkout@v4
        - name: Install dependencies
          run: |
            apt-get -y update
            apt-get -y install gcc libpath-tiny-perl libdata-float-perl cmake make build-essential git
        - name: Build (Debug)
          run: |
            make clean build BUILD_TYPE=Debug BUILD_TESTING=OFF
        - name: Build (Release)
          run: |
            make clean build BUILD_TYPE=Release BUILD_TESTING=OFF
        - name: Test (Debug)
          run: |
            make clean test VERBOSE=1 BUILD_TYPE=Debug BUILD_TESTING=ON
        - name: Test (Release)
          run: |
            make clean test VERBOSE=1 BUILD_TYPE=Release BUILD_TESTING=ON
        - name: Generate code
          run: |
            cd ubloxcfg
            rm -vf ubloxcfg_gen.[ch]
            cmake -B build -S .
            cmake --build build
            git diff --exit-code ubloxcfg_gen.[ch]

